<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOx12OG2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOx12OG2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOx12OG2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOx12OG2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOx12OG2\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ox12OG2',
    'container.build_id' => '9e508de8',
    'container.build_time' => 1708555499,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOx12OG2');
