<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQAX6zOC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQAX6zOC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQAX6zOC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQAX6zOC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQAX6zOC\App_KernelDevDebugContainer([
    'container.build_hash' => 'QAX6zOC',
    'container.build_id' => 'b9d26055',
    'container.build_time' => 1708527872,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQAX6zOC');
